from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
from .database import Base

class Product(Base):
    """
    Represents an agricultural product (e.g., 'Café de Nariño', 'Papa Pastusa').
    """
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False, unique=True)
    category = Column(String(50), nullable=False)
    is_active = Column(Boolean, default=True)

    sales_history = relationship("SalesHistory", back_populates="product")
    predictions = relationship("DemandPrediction", back_populates="product")

class SalesHistory(Base):
    """
    Historical harvest/sales data used to train the Scikit-Learn model.
    """
    __tablename__ = "sales_history"

    id = Column(Integer, primary_key=True, index=True)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=False)
    record_date = Column(DateTime, nullable=False)
    quantity_kg = Column(Float, nullable=False)
    
    # Environmental factors crucial for agricultural forecasting
    temperature_c = Column(Float, nullable=False)
    rainfall_mm = Column(Float, nullable=False)
    
    product = relationship("Product", back_populates="sales_history")

class DemandPrediction(Base):
    """
    Stores the forecasted demand generated by the Forenode AI engine.
    """
    __tablename__ = "demand_predictions"

    id = Column(Integer, primary_key=True, index=True)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=False)
    target_date = Column(DateTime, nullable=False)
    predicted_demand_kg = Column(Float, nullable=False)
    confidence_score = Column(Float, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    product = relationship("Product", back_populates="predictions")